repos:
  - repo: local
    hooks:
      - id: lint
        name: Linter
        entry: ruff check
        language: python
        types_or: [python, pyi, jupyter]
        args:
          - --fix
      - id: format
        name: Formatter
        entry: ruff format
        language: python
        types_or: [python, pyi, jupyter]
      - id: nbstripout
        name: nbstripout
        description: Strip output from Jupyter notebooks
        entry: nbstripout
        language: python
        types_or: [jupyter]
